// This file is auto-generated by scripts/generate-tool-registry.mjs.
// Do not edit this file manually.
import type { ToolManifest } from "@/lib/tool-manifest";

import { manifest as toolManifest0 } from "@/tools/markdown-preview/manifest";

export const registeredToolManifests: ToolManifest[] = [
  toolManifest0,
];
